import type { RouteConfig } from "@react-router/dev/routes";
import { index, route } from "@react-router/dev/routes";

export default [
  route("about", "about/page.tsx"),
  route("catalogs", "catalogs/page.tsx"),
  route("catalogs/:id", "catalogs/[id]/page.tsx"),
  route("characters", "characters/page.tsx"),
  route("characters/:id", "characters/[id]/page.tsx"),
  route("creators", "creators/page.tsx"),
  route("creators/:id", "creators/[id]/page.tsx"),
  route("creators/:id/edit", "creators/[id]/edit/page.tsx"),
  route("discussions", "discussions/page.tsx"),
  route("discussions/search", "discussions/search/page.tsx"),
  route(
    "discussions/:topicId/comments/:commentId",
    "discussions/[topicId]/comments/[commentId]/page.tsx",
  ),
  route("discussions/:topicId", "discussions/[topicId]/page.tsx"),
  route(
    "discussions/:topicId/posts/:postNumber",
    "discussions/[topicId]/posts/[postNumber]/page.tsx",
  ),
  route("forgot-password", "forgot-password/page.tsx"),
  route("games", "games/page.tsx"),
  route("games/:id", "games/[id]/page.tsx"),
  route("games/:id/relations", "games/[id]/relations/page.tsx"),
  route("inbox", "inbox/page.tsx"),
  route("inbox/:itemId", "inbox/[itemId]/page.tsx"),
  route("installed", "installed/page.tsx"),
  route("login", "login/page.tsx"),
  index("page.tsx"),
  route("play/:archiveVersionId", "play/[archiveVersionId]/page.tsx"),
  route("register", "register/page.tsx"),
  route("reset-password", "reset-password/page.tsx"),
  route("resources", "resources/page.tsx"),
  route("search", "search/page.tsx"),
  route("tags", "tags/page.tsx"),
  route("upload", "upload/page.tsx"),
  route("admin", "admin/layout.tsx", [
    route("archive-versions", "admin/archive-versions/page.tsx"),
    route("archive-versions/trash", "admin/archive-versions/trash/page.tsx"),
    route(
      "archive-versions/:archiveVersionId",
      "admin/archive-versions/[archiveVersionId]/page.tsx",
    ),
    route("audit", "admin/audit/page.tsx"),
    route("characters/index", "admin/characters/index/page.tsx"),
    route("characters", "admin/characters/page.tsx"),
    route("characters/:characterId", "admin/characters/[characterId]/page.tsx"),
    route("creators", "admin/creators/page.tsx"),
    route("creators/:creatorId", "admin/creators/[creatorId]/page.tsx"),
    route("discussion-tags", "admin/discussion-tags/page.tsx"),
    route("discussions/images", "admin/discussions/images/page.tsx"),
    route("discussions", "admin/discussions/page.tsx"),
    route("emojis", "admin/emojis/page.tsx"),
    route("import-jobs", "admin/import-jobs/page.tsx"),
    route(
      "import-jobs/:importJobId",
      "admin/import-jobs/[importJobId]/page.tsx",
    ),
    route("maintenance", "admin/maintenance/page.tsx"),
    index("admin/page.tsx"),
    route("permissions", "admin/permissions/page.tsx"),
    route("resources", "admin/resources/page.tsx"),
    route("resources/:id", "admin/resources/detail.tsx"),
    route("tags", "admin/tags/page.tsx"),
    route("tags/:tagId", "admin/tags/[tagId]/page.tsx"),
    route("users", "admin/users/page.tsx"),
    route("works", "admin/works/page.tsx"),
    route("works/:workId", "admin/works/[workId]/page.tsx"),
  ]),
  route("me", "me/layout.tsx", [
    route("catalogs", "me/catalogs/page.tsx"),
    route("comments", "me/comments/page.tsx"),
    route("discussions", "me/discussions/page.tsx"),
    route("favorites", "me/favorites/page.tsx"),
    route("showcase", "me/showcase/page.tsx"),
    route("emojis", "me/emojis/page.tsx"),
    route("history", "me/history/page.tsx"),
    index("me/page.tsx"),
    route("privacy", "me/privacy/page.tsx"),
    route("permissions", "me/permissions/page.tsx"),
    route("profile/email", "me/profile/email/page.tsx"),
    route("profile", "me/profile/page.tsx"),
    route("profile/password", "me/profile/password/page.tsx"),
    route("uploads", "me/uploads/page.tsx"),
    route("uploads/:workId", "me/uploads/[workId]/page.tsx"),
  ]),
  route("users/:userId", "users/[userId]/layout.tsx", [
    route("catalogs", "users/[userId]/catalogs/page.tsx"),
    route("comments", "users/[userId]/comments/page.tsx"),
    route("discussions", "users/[userId]/discussions/page.tsx"),
    route("favorites", "users/[userId]/favorites/page.tsx"),
    route("history", "users/[userId]/history/page.tsx"),
    index("users/[userId]/page.tsx"),
  ]),
  route("*", "not-found.tsx"),
] satisfies RouteConfig;
